### ISSUE TITLE
Unclear reference to #create

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/dynamic-orm-inheritance#12]
What is meant by: "The #create, #save and #find_by_name methods used here were inherited by Song from InteractiveRecord." ?

That is, where is the reference to #create?

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#19.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @jonbf,

Thanks for opening this issue and providing feedback. We're updating these materials and agree that `#create` was incorrectly referenced. This content has been updated and the reference to `#create` has been removed.

Thank you for contributing to a Learn lesson!
