### ISSUE TITLE
bin/run fails to execute

### ISSUE THREAD

**Issue by jacobsilver2** [learn-co-curriculum/dynamic-orm-inheritance#17]
Getting all sorts of errors when trying to execute bin/run

bin/run: line 1: require: command not found
bin/run: line 3: require_relative: command not found
bin/run: line 4: require_relative: command not found
bin/run: line 5: require_relative: command not found
bin/run: line 7: syntax error near unexpected token `('
bin/run: line 7: `song = Song.new(name: "Hello", album: "25")'

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. The `./bin/run` command was missing the [Hashbang](https://en.wikipedia.org/wiki/Shebang_(Unix)) declaration. We updated the command and it should work know.

As always thank you for contributing
