### ISSUE TITLE
can't actually do the run- no gem file produces the following error

### ISSUE THREAD

**Issue by wley3337** [learn-co-curriculum/dynamic-orm-inheritance#20]
/Users/willley/Desktop/Class Work/dynamic-orm-inheritance-dc-web-060418/config/environment.rb:4:in `initialize': unable to open database file (SQLite3::CantOpenException)
	from /Users/willley/Desktop/Class Work/dynamic-orm-inheritance-dc-web-060418/config/environment.rb:4:in `new'
	from /Users/willley/Desktop/Class Work/dynamic-orm-inheritance-dc-web-060418/config/environment.rb:4:in `<top (required)>'
	from /Users/willley/Desktop/Class Work/dynamic-orm-inheritance-dc-web-060418/lib/interactive_record.rb:1:in `require_relative'
	from /Users/willley/Desktop/Class Work/dynamic-orm-inheritance-dc-web-060418/lib/interactive_record.rb:1:in `<top (required)>'
	from run:4:in `require_relative'
	from run:4:in `<main>'

**Comment by drakeltheryuujin** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue, which we unfortunately do not have the capacity to support at this time. I would recommend googling around about the problem.

You can try popping into [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

I'm sorry, and good luck! 💙
