### ISSUE TITLE
String interpolation issue on line 52

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/dynamic-orm-inheritance#21]
of lib/interactive_record.rb

Wouldn't it be better if it was this: 
def self.find_by_name(name)
    sql = "SELECT * FROM #{self.table_name} WHERE name = '?'"
    DB[:conn].execute(sql, name)
  end

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.

**Comment by mackenzie-km** [comment]
Line 52 was causing me issues today when I did ruby bin/run 
ERROR: bind or column index out of range (SQLite3::RangeException)

I had to change it to 
sql = "SELECT * FROM #{self.table_name} WHERE name = ?" 
for it to run

Alternatively, I changed it to match the previous lesson
def self.find_by_name(name)
  sql = "SELECT * FROM #{self.table_name} WHERE name = '#{name}'"
  DB[:conn].execute(sql)
end

And the issue went away.
