### ISSUE TITLE
bin/run Output Doesn't Match Lab Description

### ISSUE THREAD

**Issue by renojames** [learn-co-curriculum/dynamic-orm-inheritance#22]
When running bin/run in this lab, the lab README advises that the output should be:

song = Song.new(name: "Hello", album: "25")
puts "song name: " + song.name
puts "song album: " + song.album
song.save
 
DB[:conn].execute("SELECT * FROM songs")

However, what I am getting is:

song name: Hello
song album: 25
Traceback (most recent call last):
        8: from bin/run:13:in `<main>'
        7: from /home/renojames/dynamic-orm-inheritance-v-000/lib/interactive_record.rb:53:
in `find_by_name'
        6: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.0/lib/sqlite3/database.rb:1
93:in `execute'
        5: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.0/lib/sqlite3/database.rb:1
51:in `prepare'
        4: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.0/lib/sqlite3/database.rb:1
94:in `block in execute'
        3: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.0/lib/sqlite3/statement.rb:
37:in `bind_params'
        2: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.0/lib/sqlite3/statement.rb:
37:in `each'
        1: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.0/lib/sqlite3/statement.rb:
41:in `block in bind_params'
/usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.0/lib/sqlite3/statement.rb:41:in `bind_para
m': bind or column index out of range (SQLite3::RangeException)

**Comment by UrsulaAntares** [comment]
Likewise. I'm not sure if it means we are supposed to debug it as the lab project or if it's just a buggy demonstration and we should move on. If it's the first case, and it is supposed to be broken so we can fix it, it would help if the lab description would A)say that and B) offer some scope guidance.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
