### ISSUE TITLE
Unable to run bin/run

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/dynamic-orm-inheritance#23]
As you go through the follow along you are asked to run the bin file. I get this error:

// ♥ ruby bin/run
song name: Hello
song album: 25
Traceback (most recent call last):
        8: from bin/run:13:in `<main>'
        7: from /home/TonyB/dynamic-orm-inheritance-online-web-pt-031119/lib/interactive_re
cord.rb:53:in `find_by_name'
        6: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:1
93:in `execute'
        5: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:1
51:in `prepare'
        4: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.1/lib/sqlite3/database.rb:1
94:in `block in execute'
        3: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:
37:in `bind_params'
        2: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:
37:in `each'
        1: from /usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:
41:in `block in bind_params'
/usr/local/rvm/gems/ruby-2.6.1/gems/sqlite3-1.4.1/lib/sqlite3/statement.rb:41:in `bind_para
m': bind or column index out of range (SQLite3::RangeException)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
