### ISSUE TITLE
./bin/run doesn't work

### ISSUE THREAD

**Issue by LeeyaD** [learn-co-curriculum/dynamic-orm-inheritance#24]
[23:46:37] (master) dynamic-orm-inheritance-online-web-pt-031119
// ♥ ./bin/run
song name: Hello
song album: 25
Traceback (most recent call last):
        8: from ./bin/run:13:in `<main>'
        7: from /Users/leeyadavis/Development/LearnLabs/dynamic-orm-inheritance-online-web-pt-031119/lib/interactive_record.rb:53:in `find_by_name'
        6: from /Users/leeyadavis/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
        5: from /Users/leeyadavis/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
        4: from /Users/leeyadavis/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:138:in `blockin execute'
        3: from /Users/leeyadavis/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:37:in `bind_params'
        2: from /Users/leeyadavis/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:37:in `each'
        1: from /Users/leeyadavis/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:41:in `blockin bind_params'
/Users/leeyadavis/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:41:in `bind_param': column index out of range (SQLite3::RangeException)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
