### ISSUE TITLE
self.find_by_name causes column error

### ISSUE THREAD

**Issue by aparkening** [learn-co-curriculum/dynamic-orm-inheritance#25]
Saw the following error when running `puts Song.find_by_name("Hello")` from bin/run:

> Traceback (most recent call last):
>         8: from bin/run:47:in `<main>'
>         7: from /Users/aaronparkening/Dev/Flatiron/code/dynamic-orm-inheritance-online-web-pt-041519/lib/interactive_record.rb:55:in `find_by_name'
>         6: from /Users/aaronparkening/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
>         5: from /Users/aaronparkening/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:95:in `prepare'
>         4: from /Users/aaronparkening/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:138:in `block in execute'
>         3: from /Users/aaronparkening/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:37:in `bind_params'
>         2: from /Users/aaronparkening/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:37:in `each'
>         1: from /Users/aaronparkening/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:41:in `block in bind_params'
> /Users/aaronparkening/.rvm/gems/ruby-2.6.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:41:in `bind_param': column index out of range (SQLite3::RangeException)

Directly running the SQL query completes correctly.
```
sql = "SELECT * FROM songs WHERE name = 'Hello'"
puts DB[:conn].execute(sql)
```

**Comment by micahshute** [comment]
Check out issue #26 for fix

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
