### ISSUE TITLE
Syntax Error line 52 interactive_record.rb

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/dynamic-orm-inheritance#26]
Line 52 of interactive_record.rb has a syntax error, with quotations around the question mark that break the code. 

Specifically
```ruby
sql = "SELECT * FROM #{self.table_name} WHERE name = '?'"
```

should be
```ruby
sql = "SELECT * FROM #{self.table_name} WHERE name = ?"
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
