### ISSUE TITLE
Possible redundant code re: section titled "The Child Class"

### ISSUE THREAD

**Issue by miclp** [learn-co-curriculum/dynamic-orm-inheritance#8]
Lines 5 to 7 in song.rb contain the attr_accessor code that also seems to be present in lines 23-25 of interactive_record.rb.  I can't seem to distinguish the difference in functionality... perhaps it's only needed in one place?

**Comment by AnnJohn** [comment]
@PeterBell this needs to be vetted before someone fixes it

**Comment by pletcher** [comment]
Fixed in https://github.com/learn-co-curriculum/dynamic-orm-inheritance/pull/10
