### ISSUE TITLE
Bin/rub file is referring to a wrong database.

### ISSUE THREAD

**Issue by talgoldfus** [learn-co-curriculum/dynamic-orm-inheritance#9]
bin/rub file 

---

require 'sqlite3'

Original file :
Line 4:  DB = {:conn => SQLite3::Database.new("db/**students**.db")} 
Should be DB = {:conn => SQLite3::Database.new("db/**songs**.db")} .

Other wise would raise an error "dynamic-orm-inheritance-web-0616/config/environment.rb:4:in `initialize': unable to open database file (SQLite3::CantOpenException)"

**Comment by AnnJohn** [comment]
@PeterBell this needs to vetted before someone fixes it.

**Comment by pletcher** [comment]
Fixed in https://github.com/learn-co-curriculum/dynamic-orm-inheritance/pull/10
